CREATE DATABASE IF NOT EXISTS project;
use project;

DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS TEACHER;
DROP TABLE IF EXISTS COURSE;


CREATE TABLE IF NOT EXISTS STUDENT (  
NAME VARCHAR (20) NOT NULL,  
DOB VARCHAR (20)  NOT NULL,  
ADDRESS CHAR (25),
PASSWORD VARCHAR (20) NOT NULL,
PHONENUMBER VARCHAR (20) ,
EMAIL VARCHAR (20) NOT NULL,
PRIMARY KEY (EMAIL)  
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS TEACHER (  
NAME VARCHAR (20) NOT NULL,  
DOB VARCHAR (20)  NOT NULL,  
ADDRESS CHAR (25),
PASSWORD VARCHAR (20) NOT NULL,
PHONENUMBER VARCHAR (20) ,
EMAIL VARCHAR (20) NOT NULL,
PRIMARY KEY (EMAIL)  
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS COURSE (  
ID VARCHAR (20)   NOT NULL,  
NAME VARCHAR (50) NOT NULL, 
PRIMARY KEY (ID)  
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS COURSE (  
ID VARCHAR (20)   NOT NULL,  
NAME VARCHAR (50) NOT NULL, 
PRIMARY KEY (ID)  
)ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS REGISTRATION (
ID int NOT NULL AUTO_INCREMENT,
S_EMAIL VARCHAR (20) NOT NULL,
T_EMAIL VARCHAR (20) NOT NULL,
CID VARCHAR (20) NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT S_FK FOREIGN KEY (S_EMAIL) REFERENCES STUDENT(EMAIL),
CONSTRAINT T_FK FOREIGN KEY (T_EMAIL) REFERENCES TEACHER(EMAIL),
CONSTRAINT C_FK FOREIGN KEY (CID) REFERENCES COURSE(ID)
)ENGINE=INNODB;


INSERT INTO STUDENT(NAME,DOB,ADDRESS,PASSWORD,PHONENUMBER,EMAIL) VALUES ("Bilal", "1-1-1999", "K-Block, Johar Town", "123456", "03331234567", "bilal@gmail.com");
INSERT INTO STUDENT(NAME,DOB,ADDRESS,PASSWORD,PHONENUMBER,EMAIL) VALUES ("Ali", "1-1-1999", "J-Block, Johar Town", "123456", "03331234567", "ali@gmail.com");

INSERT INTO TEACHER(NAME,DOB,ADDRESS,PASSWORD,PHONENUMBER,EMAIL) VALUES ("Sarim", "1-1-1982", "B-Block, Faisal Town", "123456", "03331234567", "sarim@gmail.com");
INSERT INTO TEACHER(NAME,DOB,ADDRESS,PASSWORD,PHONENUMBER,EMAIL) VALUES ("Maryam", "1-1-1984", "A-Block, Model Town", "123456", "03331234567", "maryam@gmail.com");

INSERT INTO COURSE(ID,NAME) VALUES ("CS500", "Design & Analysis of Algorithms");
INSERT INTO COURSE(ID,NAME)  VALUES ("CS450", "Artificial Intelligence");

INSERT INTO REGISTRATION(S_EMAIL, T_EMAIL, CID) VALUES ("bilal@gmail.com", "sarim@gmail.com", "CS500");
INSERT INTO REGISTRATION(S_EMAIL, T_EMAIL, CID) VALUES ("ali@gmail.com", "maryam@gmail.com", "CS450");